### ISSUE TITLE
[BUG] The software can not see the large dictionary

### ISSUE THREAD

**Issue by k566o** [Dadangdut33/Speech-Translate#22]
Software can not see the large dictionary , so I delete it, software successfully downloads it, but then can not see it, will keep asking to download large dictionary
screencap
https://www.youtube.com/watch?v=3zzrkz5oeUU

Downloading of other dictionaries works fine

**Comment by Dadangdut33** [comment]
hmm interesting, i will check this out

**Comment by Dadangdut33** [comment]
Hmm it seems that the cause is because of the model name being different. I hard coded it as `large` but there seems to be an update that i missed, the model is downloaded as large-v2. In the meanwhile you could try to rename the `large-v2.pt` as `large.pt`


I will provide a fix asap, Thanks for letting me know
