### ISSUE TITLE
Feature Request: Batch Uploading of audio files for processing.

### ISSUE THREAD

**Issue by MRAWAY77** [Dadangdut33/Speech-Translate#4]
I would like to check if there is an option to batch upload a zip folders of multiple audio files for a single processing?

**Comment by Dadangdut33** [comment]
multiple audio files for a single processing is now possible along with srt exports, thanks for the request submission :)

**Comment by MRAWAY77** [comment]
Hi Thanks! I see that you have included a new feature in the exportation.... am i right to say you have included speaker diarization in the transcription as a form of enhancement? or is it originally from the https://github.com/openai/whisper repo that you reference from?

**Comment by Dadangdut33** [comment]
> Hi Thanks! I see that you have included a new feature in the exportation.... am i right to say you have included speaker diarization in the transcription as a form of enhancement? or is it originally from the https://github.com/openai/whisper repo that you reference from?

I think it's not speaker diarization, just timeframe of each segment because it is actually based from audio segmentation from whisper result itself and i actually made a wrong reference there it should be from [this repo actually](https://github.com/marferca/yt-whisper-demo/). I found that method in a [discussion](https://github.com/openai/whisper/discussions/262) (which is in the whisper official repository)
